import React, {useState, useEffect, useMemo, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {geoOrthographic, geoPath, geoGraticule10, geoInterpolate, geoDistance} from 'd3-geo';
import {feature} from 'topojson-client';
import world from 'world-atlas/countries-110m.json';
import {ArrowUpRight, ArrowRight, ArrowLeft, Play, Pause, RotateCcw, Crosshair, Globe2, Code2, Copy, Check, Move, MapPin, Plus, Minus} from 'lucide-react';
import {haversine, RADIUS} from './math';
import './style.css';
const land=feature(world,world.objects.countries);
const presets={ 'Across continents':[[33.5731,-7.5898],[48.8566,2.3522]], 'A local delivery':[[33.5731,-7.5898],[33.589,-7.61]], 'Across the date line':[[20,170],[20,-170]], 'A quarter of Earth':[[0,0],[0,90]]};
const fmt=(v,n=4)=>v.toLocaleString('en-US',{maximumFractionDigits:n});
const coords=p=>`${Math.abs(p[0]).toFixed(2)}° ${p[0]>=0?'N':'S'} · ${Math.abs(p[1]).toFixed(2)}° ${p[1]>=0?'E':'W'}`;
const python=`import numpy as np\n\n# Coordinates: degrees → radians\nlat1 = np.radians(df["Restaurant_latitude"])\nlon1 = np.radians(df["Restaurant_longitude"])\nlat2 = np.radians(df["Delivery_location_latitude"])\nlon2 = np.radians(df["Delivery_location_longitude"])\n\ndlat = lat2 - lat1\ndlon = lon2 - lon1\n\na = (np.sin(dlat / 2) ** 2\n     + np.cos(lat1) * np.cos(lat2)\n     * np.sin(dlon / 2) ** 2)\n\nc = 2 * np.arcsin(np.sqrt(np.clip(a, 0, 1)))\ndf["distance_km"] = 6371 * c`;
function Globe({points,setPoints,target,setTarget,rotation,setRotation,spinning,setSpinning,grid,zoom,setZoom}) {
 const svgRef=useRef(null),drag=useRef(null);
 useEffect(()=>{
   const svg=svgRef.current;
   const wheel=e=>{
     e.preventDefault();
     setSpinning(false);
     const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?600:1);
     setZoom(z=>Math.max(1,Math.min(6,z*Math.exp(-delta*.0015))));
   };
   svg.addEventListener('wheel',wheel,{passive:false});
   return()=>svg.removeEventListener('wheel',wheel);
 },[setZoom,setSpinning]);
 const radius=244*zoom;
 const projection=geoOrthographic().translate([360,300]).scale(radius).rotate(rotation).clipAngle(90);
 const path=geoPath(projection);
 const p1=[points[0][1],points[0][0]],p2=[points[1][1],points[1][0]];
 const interpolate=geoInterpolate(p1,p2);
 const route={type:'LineString',coordinates:Array.from({length:161},(_,i)=>interpolate(i/160))};
 const front=projection.invert([360,300]);
 function position(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svgRef.current.getScreenCTM().inverse());return [p.x,p.y];}
 function down(e){if(e.button!==0)return;svgRef.current.setPointerCapture(e.pointerId);drag.current={start:position(e),rot:rotation,moved:false};setSpinning(false);}
 function move(e){if(!drag.current)return;const p=position(e),dx=p[0]-drag.current.start[0],dy=p[1]-drag.current.start[1];if(Math.hypot(dx,dy)>4)drag.current.moved=true;if(drag.current.moved)setRotation([drag.current.rot[0]+dx*.3/zoom,Math.max(-85,Math.min(85,drag.current.rot[1]-dy*.3/zoom)),0]);}
 function up(e){if(!drag.current)return;const p=position(e);if(!drag.current.moved&&target!==null&&Math.hypot(p[0]-360,p[1]-300)<=radius){const ll=projection.invert(p);if(ll&&ll.every(Number.isFinite)){setPoints(old=>old.map((v,i)=>i===target?[+ll[1].toFixed(4),+ll[0].toFixed(4)]:v));setTarget(target===0?1:null);}}drag.current=null;}
 return <svg ref={svgRef} className={'globe '+(target!==null?'placing':'')} viewBox="0 0 720 600" role="img" aria-label="Interactive Earth. Drag to rotate. Scroll to zoom. Choose Place A or Place B, then click Earth. Coordinate fields provide a keyboard alternative." onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>drag.current=null}>
 <defs><radialGradient id="ocean" cx="33%" cy="25%"><stop offset="0%" stopColor="#253d33"/><stop offset="75%" stopColor="#152b23"/><stop offset="100%" stopColor="#0c1c16"/></radialGradient><radialGradient id="shade" cx="30%" cy="30%" r="74%"><stop offset="45%" stopColor="#030b06" stopOpacity="0"/><stop offset="100%" stopColor="#030b06" stopOpacity=".65"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="3"/></filter></defs>
 <circle cx="360" cy="300" r={radius+24} fill="none" stroke="#bce49f" strokeOpacity=".08"/><circle cx="360" cy="300" r={radius+12} fill="none" stroke="#bce49f" strokeOpacity=".15"/>
 <path d={path({type:'Sphere'})} fill="url(#ocean)" stroke="#718a6b" strokeWidth="1"/>
 {grid&&<path d={path(geoGraticule10())} fill="none" stroke="#accb9e" strokeOpacity=".13" strokeWidth=".65"/>}
 <path d={path(land)} fill="#677f55" stroke="#233d2c" strokeWidth=".55"/>
 <circle cx="360" cy="300" r={radius} fill="url(#shade)" pointerEvents="none"/>
 <path d={path(route)} fill="none" stroke="#dcf4a0" strokeWidth="7" opacity=".3" filter="url(#glow)"/>
 <path d={path(route)} fill="none" stroke="#def8a5" strokeWidth="2.6"/>
 {points.map((p,i)=>{const ll=[p[1],p[0]],pos=projection(ll);return geoDistance(ll,front)<Math.PI/2&&<g key={i} transform={`translate(${pos})`}><circle r="12" fill={i?'#f7b18d':'#e1f4aa'} fillOpacity=".15"/><circle r="5" fill={i?'#f7b18d':'#e1f4aa'} stroke="#17251b" strokeWidth="2"/><text x="11" y="-12" fill={i?'#f7b18d':'#e1f4aa'} fontSize="15" fontWeight="600">{i?'B':'A'}</text></g>;})}
 </svg>;
}
function App(){
 const [points,setPoints]=useState(presets['Across continents']);
 const [zoom,setZoom]=useState(1);
 const [rotation,setRotation]=useState([0,-30,0]);
 const [spinning,setSpinning]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [target,setTarget]=useState(null),[grid,setGrid]=useState(true),[step,setStep]=useState(0),[copied,setCopied]=useState(false),[preset,setPreset]=useState('Across continents');
 const values=useMemo(()=>haversine(...points),[points]);
 useEffect(()=>{if(!spinning)return;let frame,last;function tick(now){if(last)setRotation(r=>[r[0]+Math.min(now-last,60)*.0025,r[1],0]);last=now;frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[spinning]);
 function choosePreset(name){const p=presets[name];setPreset(name);setPoints(p);setZoom(1);setSpinning(false);setTarget(null);const mid=geoInterpolate([p[0][1],p[0][0]],[p[1][1],p[1][0]])(.5);setRotation([-mid[0],-mid[1],0]);}
 function editPoint(i,j,v){if(v==='')return;const n=Number(v),max=j===0?90:180;if(!Number.isFinite(n)||Math.abs(n)>max)return;setSpinning(false);setPreset('Custom points');setPoints(ps=>ps.map((p,k)=>k===i?p.map((x,l)=>l===j?n:x):p));}
 const lessons=[
 {title:'Start with two addresses on Earth.',body:'Latitude tells you how far north or south you are. Longitude tells you how far east or west. Together, they locate a point. Pick two points above, or enter their coordinates.',formula:'A = (latitude₁, longitude₁)   B = (latitude₂, longitude₂)',result:`A (${fmt(points[0][0])}°, ${fmt(points[0][1])}°) → B (${fmt(points[1][0])}°, ${fmt(points[1][1])}°)`,code:'origin = (latitude1, longitude1)'},
 {title:'Give trigonometry the units it expects.',body:'Our coordinates are in degrees. Sine and cosine work with radians: one full turn is 360° or 2π radians. Multiply each coordinate by π / 180.',formula:'radians = degrees × π / 180',result:`φ₁ = ${fmt(values.p1,6)} rad   ·   φ₂ = ${fmt(values.p2,6)} rad`,code:'lat1 = np.radians(df["Restaurant_latitude"])'},
 {title:'Measure the angular separation.',body:'Subtract the origin from the destination. Δφ measures the north–south difference; Δλ measures the longitude difference. These are angles, not kilometres. The formula also works across the date line.',formula:'Δφ = φ₂ − φ₁     Δλ = λ₂ − λ₁',result:`Δφ = ${fmt(values.dp,6)} rad   ·   Δλ = ${fmt(values.dl,6)} rad`,code:'dlat = lat2 - lat1\ndlon = lon2 - lon1'},
 {title:'Let Earth’s curvature do its part.',body:'Combine the latitude and longitude differences. The cosine terms reduce the longitude contribution near the poles, where meridians converge. The intermediate value a has no units.',formula:'a = sin²(Δφ/2) + cos(φ₁) cos(φ₂) sin²(Δλ/2)',result:`a = ${values.a.toPrecision(7)}`,code:'a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2'},
 {title:'Find the angle at Earth’s centre.',body:'The square root and inverse sine recover the central angle c. This is the angle between two radii pointing at your locations. Clip a to [0, 1] to guard against tiny floating-point rounding errors.',formula:'c = 2 arcsin(√a)',result:`c = ${fmt(values.c,7)} rad = ${fmt(values.c*180/Math.PI,3)}°`,code:'c = 2 * np.arcsin(np.sqrt(np.clip(a, 0, 1)))'},
 {title:'Turn that angle into a distance.',body:'Arc length equals radius times angle in radians. Multiply c by Earth’s approximate mean radius, 6,371 km. You now have one distance feature for each delivery.',formula:'d = R × c     R = 6,371 km',result:`6,371 × ${fmt(values.c,7)} = ${fmt(values.distance,3)} km`,code:'df["distance_km"] = 6371 * c'}
 ];
 const current=lessons[step];
 async function copy(){try{await navigator.clipboard.writeText(python);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setCopied(false);}}
 return <><header className="header"><a href="#" className="brand"><span className="brand-icon">◔</span> arc<span className="brand-dot">.</span></a><nav><a href="#explore">Explore</a><a href="#formula">The formula</a><a href="#code">In your project <ArrowUpRight size={14}/></a></nav><span className="header-label">AN INTERACTIVE FIELD GUIDE</span></header>
 <main><section className="intro"><div className="eyebrow"><span/> GEOGRAPHY MEETS A LITTLE MATH</div><h1>A little distance.<br/><em>A world of understanding.</em></h1><p>Two points. One curved planet. Discover how the Haversine formula<br className="desktop"/> turns coordinates into kilometres — one small step at a time.</p><a className="intro-link" href="#explore">Let’s connect the dots <ArrowRight size={17}/></a><span className="edition">01 / THE HAVERSINE FORMULA</span></section>
 <section id="explore" className="explorer"><div className="globe-panel"><div className="panel-top"><span><span className="live-dot"/> YOUR LITTLE PLANET</span><button onClick={()=>setGrid(!grid)} aria-pressed={grid}>Grid {grid?'on':'off'}</button></div><Globe points={points} setPoints={p=>{setPreset('Custom points');setPoints(p);}} target={target} setTarget={setTarget} rotation={rotation} setRotation={setRotation} spinning={spinning} setSpinning={setSpinning} grid={grid} zoom={zoom} setZoom={setZoom}/><div className="globe-bottom"><span><Move size={14}/> Drag to rotate · Scroll to zoom</span><div className="globe-actions"><button aria-label="Zoom out" disabled={zoom<=1} onClick={()=>{setZoom(z=>Math.max(1,z/1.4));setSpinning(false);}}><Minus size={17}/></button><button className="zoom-level" aria-label="Reset zoom" title="Reset zoom" onClick={()=>setZoom(1)}>{zoom.toFixed(1)}×</button><button aria-label="Zoom in" disabled={zoom>=6} onClick={()=>{setZoom(z=>Math.min(6,z*1.4));setSpinning(false);}}><Plus size={17}/></button><button aria-label={spinning?'Pause globe rotation':'Start globe rotation'} onClick={()=>setSpinning(!spinning)}>{spinning?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Center view on route" onClick={()=>{const m=geoInterpolate([points[0][1],points[0][0]],[points[1][1],points[1][0]])(.5);setRotation([-m[0],-m[1],0]);setSpinning(false);}}><Crosshair size={18}/></button></div></div><div className="placing-status" aria-live="polite">{target!==null?`Click on Earth to place point ${target===0?'A':'B'}. Drag to reach the other side.`:'The bright arc is the shortest path over a spherical Earth.'}</div></div>
 <aside className="controls"><div className="controls-heading"><h2>Make a connection.</h2><button aria-label="Reset points" onClick={()=>choosePreset('Across continents')}><RotateCcw size={17}/></button></div><p>Choose a journey, then make it your own.</p><label className="preset-label">TRY A JOURNEY<select value={preset} onChange={e=>choosePreset(e.target.value)}>{preset==='Custom points'&&<option>Custom points</option>}{Object.keys(presets).map(x=><option key={x}>{x}</option>)}</select></label>
 {points.map((p,i)=><div className={'point-card point-'+i} key={i}><div className="point-heading"><span className="point-letter">{i?'B':'A'}</span><span>{i?'Destination':'Origin'}</span><button className={target===i?'selected':''} onClick={()=>{setTarget(target===i?null:i);setSpinning(false);}} aria-pressed={target===i}><MapPin size={13}/> {target===i?'Click globe':'Place '+(i?'B':'A')}</button></div><div className="coordinate-inputs">{['Latitude','Longitude'].map((name,j)=><label key={name}>{name}<input type="number" min={j===0?-90:-180} max={j===0?90:180} step="0.0001" aria-label={`${i?'Destination':'Origin'} ${name}`} value={p[j]} onChange={e=>editPoint(i,j,e.target.value)}/></label>)}</div><small>{coords(p)}</small></div>)}
 <div className="distance"><span>SURFACE DISTANCE</span><div data-testid="distance">{fmt(values.distance,2)} <small>km</small></div><p>Along the curve. As the crow flies.</p></div><div className="radius-note"><Globe2 size={15}/> Earth radius <strong>6,371 km</strong></div></aside></section>
 <section className="context"><span className="section-number">A SMALL BUT IMPORTANT DETAIL</span><p>This arc follows Earth’s surface.<br/><strong>It doesn’t follow roads.</strong></p><div>Haversine treats Earth as a sphere. Geodesic calculations use a more accurate ellipsoid. Neither knows about streets, bridges, or traffic — that needs a routing engine.</div></section>
 <section id="formula" className="formula-section"><div className="section-heading"><div><span className="eyebrow">FROM TWO POINTS TO ONE NUMBER</span><h2>The math, without the mystery.</h2></div><p>Every value below follows your points above.</p></div><div className="lesson-layout"><div className="steps" aria-label="Formula steps">{['Choose your points','Degrees → radians','Find the differences','Account for curvature','Recover the angle','Multiply by Earth’s radius'].map((name,i)=><button key={name} className={step===i?'active':''} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span>{name}<ArrowUpRight size={15}/></button>)}</div><article className="lesson"><span className="lesson-index">STEP {step+1} OF 6</span><h3>{current.title}</h3><p>{current.body}</p><div className="equation">{current.formula}</div><div className="live-result"><span>WITH YOUR POINTS</span><output>{current.result}</output></div><pre><code>{current.code}</code></pre><div className="lesson-footer"><button disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Previous</button><span>{step+1} / 6</span><button disabled={step===5} onClick={()=>setStep(step+1)}>Next step <ArrowRight size={16}/></button></div></article></div></section>
 <section id="code" className="code-section"><div><span className="eyebrow">BACK TO YOUR DELIVERY PROJECT</span><h2>45,000 rows.<br/><em>Zero API requests.</em></h2><p>NumPy applies the same calculation to entire columns. Four coordinate columns become one useful feature: <code>distance_km</code>.</p><ul><li><Check size={16}/> Runs locally, without a Python row loop</li><li><Check size={16}/> Missing coordinates stay missing</li><li><Check size={16}/> Use the same calculation at prediction time</li></ul><p className="code-note">Start with numeric, validated coordinates. Keep the original coordinates in your source data. This feature measures surface distance, not road distance.</p></div><div className="code-box"><div><span><Code2 size={16}/> distance_feature.py</span><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy code'}</button></div><pre><code>{python}</code></pre></div></section>
 <section className="takeaway"><span>TAKE IT WITH YOU</span><h2>Coordinates → angle → distance.</h2><p>That’s the whole journey. The rest is understanding the curve.</p><a href="#explore">Try another journey <ArrowUpRight size={17}/></a></section></main><footer><a href="#" className="brand">◔ arc.</a><span>A small exploration of a big planet.</span><div>Map: <a href="https://github.com/topojson/world-atlas" target="_blank" rel="noreferrer">Natural Earth / World Atlas</a> · <a href="https://d3js.org/d3-geo/projection" target="_blank" rel="noreferrer">D3 geography</a></div></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
